export default {
    color1:{
        mainColor:"#075e54",
        secondColor:"#d5e3d7",
        bgColor:"#fff",
        pannelColor:"#fff",
        fontColor:"#075e54",
        dark:false
    },
    color2:{
        mainColor:"#f30826",
        secondColor:"#e3d5d5",
        bgColor:"#fff",
        pannelColor:"#fff",
        fontColor:"#f30826",
        dark:false
    },
    color3:{
        mainColor:"#3c008b",
        secondColor:"#dfd5e3",
        bgColor:"#fff",
        pannelColor:"#fff",
        fontColor:"#3c008b",
        dark:false
    },
    color4:{
        mainColor:"purple",
        secondColor:"#dfd5e3",
        bgColor:"#fff",
        pannelColor:"#fff",
        fontColor:"purple",
        dark:false
    },
    color5:{
        mainColor:"blue",
        secondColor:"#d5d5e3",
        bgColor:"#fff",
        pannelColor:"#fff",
        fontColor:"blue",
        dark:false
    },
    color6:{
        mainColor:"#f1831d",
        secondColor:"#e3dbd5",
        bgColor:"#fff",
        pannelColor:"#fff",
        fontColor:"#f1831d",
        dark:false
    },
    color7:{
        mainColor:"#d5342b",
        secondColor:"#e3d5d5",
        bgColor:"#fff",
        pannelColor:"#fff",
        fontColor:"#d5342b",
        dark:false
    },
    color8:{
        mainColor:"#e9118f",
        secondColor:"#e3d5e1",
        bgColor:"#fff",
        pannelColor:"#fff",
        fontColor:"#e9118f",
        dark:false
    },
    color9:{
        mainColor:"#5fa505",
        secondColor:"#d5e3d7",
        bgColor:"#fff",
        pannelColor:"#fff",
        fontColor:"#5fa505",
        dark:false
    },
    color10:{
        mainColor:"#4272f1",
        secondColor:"#00ffff",
        bgColor:"#fff",
        pannelColor:"#fff",
        fontColor:"#4272f1",
        dark:false
    },
    color11:{
        mainColor:"#eee428",
        secondColor:"#d5e3d7",
        bgColor:"#fff",
        pannelColor:"#fff",
        fontColor:"#eee428",
        dark:false
    },
    color12:{
        mainColor:"#1D232C",
        secondColor:"#345466",
        bgColor:"#161B21",
        pannelColor:"#fff",
        fontColor:"#fff",
        placeHoleder:"#aaa",
        dark:true
    },
    light:"#c7defa",
    lightColor:"#000",
    buttonDarkBackground:"#2F2F41",
    buttonLightBackground:"#aaa",
    mainColor:"#075e54",
    secondColor:"#93ecd0",
    waiting:"orange",
    thirdColor:"#fff",
    dark:"#161525",
    darkColor:"#404040",
}